### ISSUE TITLE
Any progress on scraping this data?

### ISSUE THREAD

**Issue by bobokeke0** [saulshanabrook/pfaf-data#1]
I've thought about using cheerio to grabs all the plant details into a json or csv format. I'm wondering if you ever made any progress on grabing the database?

**Comment by saulshanabrook** [comment]
@bobokeke0 Sorry, just seeing your comment now! 

I did have some success. All the data is scraped in a sqlite database, which you should be able to convert to CSV if you like! 

let me know if you have any questions about this.
